### ISSUE TITLE
Duplicate share on mainnet

### ISSUE THREAD

**Issue by Retropex** [benjamin-wilson/public-pool#54]
same problem of #50 but on mainnet:

```
0|main  | {"id":112,"result":null,"error":[22,"Duplicate share",""]}
0|main  | QueryFailedError: SQLITE_ERROR: no such column: NaN
0|main  |     at handler (/home/leo/.public-pool/src/driver/sqlite/SqliteQueryRunner.ts:113:26)
0|main  |     at Statement.errBack (/home/leo/.public-pool/node_modules/sqlite3/lib/sqlite3.js:15:21) {
0|main  |   query: 'UPDATE "client_entity" SET "hashRate" = NaN, "deletedAt" = ?, "updatedAt" = ? WHERE ("address" = ? AND "clientName" = ? AND "sessionId" = ?)',
0|main  |   parameters: [
0|main  |     undefined,
0|main  |     '0NaN-aN-aN aN:aN:aN.NaN',
0|main  |     '******',
0|main  |     'bitaxe',
0|main  |     '1c1b40b3'
0|main  |   ],
0|main  |   driverError: [Error: SQLITE_ERROR: no such column: NaN] {
0|main  |     errno: 1,
0|main  |     code: 'SQLITE_ERROR'
0|main  |   },
0|main  |   errno: 1,
0|main  |   code: 'SQLITE_ERROR'
0|main  | }
```

<img width="1065" alt="image" src="https://github.com/user-attachments/assets/c5e05c41-8d58-4690-a1c6-e581defb67a8">

**Comment by Retropex** [comment]
Apparently the problem isn't here on a old commit deed775d5561a2c9a21dfe595260225ec676344f (chosen randomly for testing)

**Comment by benjamin-wilson** [comment]
Testing this again tonight, are you able to reproduce this still? I have not been able to reproduce it. Any reproduction steps?

**Comment by owenashurst** [comment]
> Testing this again tonight, are you able to reproduce this still? I have not been able to reproduce it. Any reproduction steps?

I'm able to reproduce this on the TestNet at least. Seems like the first few shares are fine, then it starts submitting a lot of duplicates. ZMQ enabled etc. I'm running V27.0.0 of Bitcoin Core.

**Comment by KillerInk** [comment]
here is the patch^^

https://github.com/benjamin-wilson/public-pool/pull/102

**Comment by Detroitin** [comment]
on umbrel, what triggers it for me is when I open the UI on a separate device" ill start it up point miners, showing they are authorized and then I open the UI is when it trips to duplicate share? with only one miner it dosent seem to do it LOL? SOUNDS STUPID but??? that definitely plays a part also?? im no dev or coder" but playing around and trying different things that is what ive found happens.. ON MY SETUP ive noticed this but seems to be something to do with the UI connection. I could be totally off but that is where I can trigger it.. when I introduce the UI.  on testnet. still gets blocks.. lol? hope this helps if its not solved completely..
