### ISSUE TITLE
Problem to build docker image

### ISSUE THREAD

**Issue by Demontager** [benjamin-wilson/public-pool#71]
Downloaded the latest public-pool and tried it to build in docker. It's failed.

```
Removing intermediate container 1dd4e3e4c38d
 ---> 2facc2681654
Step 4/11 : WORKDIR /build
 ---> Running in ce6f5cea865b
Removing intermediate container ce6f5cea865b
 ---> 5de4b7f91131
Step 5/11 : COPY . .
 ---> 79a2b48f3b70
Step 6/11 : RUN npm i && npm run build
 ---> Running in 4507dd0bba87
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'undici@6.19.8',
npm WARN EBADENGINE   required: { node: '>=18.17' },
npm WARN EBADENGINE   current: { node: 'v18.16.1', npm: '9.5.1' }
npm WARN EBADENGINE }
npm WARN deprecated superagent@8.1.2: Please upgrade to v9.0.0+ as we have fixed a public vulnerability with formidable dependency. Note that v9.0.0+ requires Node.js v14.18.0+. See https://github.com/ladjs/superagent/pull/1800 for insight. This project is supported and maintained by the team at Forward Email @ https://forwardemail.net
npm WARN deprecated gauge@4.0.4: This package is no longer supported.
npm WARN deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated npmlog@6.0.2: This package is no longer supported.
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm WARN deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
npm WARN deprecated zeromq@6.0.0-beta.19: please upgrade to ^6.0.4
npm WARN deprecated @types/cron@2.4.0: This is a stub types definition. cron provides its own type definitions, so you do not need this installed.
npm WARN deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported

added 1002 packages, and audited 1003 packages in 22m

176 packages are looking for funding
  run `npm fund` for details

21 vulnerabilities (5 low, 10 moderate, 6 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
npm notice 
npm notice New major version of npm available! 9.5.1 -> 10.9.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.9.0>
npm notice Run `npm install -g npm@10.9.0` to update!
npm notice 

> public-pool@0.0.1 build
> nest build

src/models/StratumV1Client.ts:100:27 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(intervalId: string | number | Timeout): void', gave the following error.
    Argument of type 'Timer' is not assignable to parameter of type 'string | number | Timeout'.
      Property '[Symbol.dispose]' is missing in type 'Timer' but required in type 'Timeout'.
  Overload 2 of 2, '(id: number): void', gave the following error.
    Argument of type 'Timer' is not assignable to parameter of type 'number'.

100             clearInterval(work);
                              ~~~~

  node_modules/@types/node/timers.d.ts:76:17
    76                 [Symbol.dispose](): void;
                       ~~~~~~~~~~~~~~~~~~~~~~~~~
    '[Symbol.dispose]' is declared here.

Found 1 error(s).

The command '/bin/sh -c npm i && npm run build' returned a non-zero code: 1
dem@xeon:~/public-pool$ 


```

BTW. It's also failing when trying to run with npm

```
$ npm run start

> public-pool@0.0.1 start
> nest start


/home/dem/public-pool/node_modules/@nestjs/schedule/dist/decorators/interval.decorator.js:12
    const [name, intervalTimeout] = (0, util_1.isString)(nameOrTimeout)
                                                        ^
TypeError: (0 , util_1.isString) is not a function
    at Interval (/home/dem/public-pool/node_modules/@nestjs/schedule/dist/decorators/interval.decorator.js:12:57)
    at Object.<anonymous> (/home/dem/public-pool/src/ORM/client/client.service.ts:25:14)
    at Module._compile (node:internal/modules/cjs/loader:1568:14)
    at Object..js (node:internal/modules/cjs/loader:1711:10)
    at Module.load (node:internal/modules/cjs/loader:1328:32)
    at Function._load (node:internal/modules/cjs/loader:1138:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1350:12)
    at require (node:internal/modules/helpers:138:16)

```
npm -v 10.9.0 
node -v  v23.0.0

**Comment by remcoros** [comment]
what Dockerfile did you use? https://github.com/benjamin-wilson/public-pool/blob/master/Dockerfile#L29 says it's using node 18, not 23.

**Comment by Demontager** [comment]
> what Dockerfile did you use?

I was using the one available inside the repo, anyway i was able to start docker container and then i checked node and npm versions being used by docker container. 
node -v
v18.16.1
npm -v
9.5.1

Then i have installed same version of node on main system and was able to run public-pool, however seems it can't communicate with Bitcoin core rpc server.

below bitcoin_testnet.conf, Bitcoin Core version v27.0.0
``` 
testnet=1
txindex=1
server=1
[test]
rpcport=5000
rpcallowip=192.168.1.0/24
rpcuser=dem
rpcpassword=mypassword
rpcbind=0.0.0.0

```
.env file
```
# bitcoin node running in your private network 192.168.1.0/24
BITCOIN_RPC_URL=http://dem:171282@192.168.1.181:5000

# bitcoin node running undockered on the same PC
# needs to add rpcallowip=172.16.0.0/12 to your bitcoin.conf
#BITCOIN_RPC_URL=http://host.docker.internal

BITCOIN_RPC_USER=dem
BITCOIN_RPC_PASSWORD=mypassword
BITCOIN_RPC_PORT=5000
BITCOIN_RPC_TIMEOUT=10000

# You can use this instead of BITCOIN_RPC_USER and BITCOIN_RPC_PASSWORD
BITCOIN_RPC_COOKIEFILE=

# Enable in bitcoin.conf with
# zmqpubrawblock=tcp://*:3000
# BITCOIN_ZMQ_HOST="tcp://192.168.1.100:3000"

API_PORT=3334
STRATUM_PORT=3333

#optional telegram bot
#TELEGRAM_BOT_TOKEN=

#optional discord bot
#DISCORD_BOT_CLIENTID=
#DISCORD_BOT_GUILD_ID=
#DISCORD_BOT_CHANNEL_ID=

#optional
DEV_FEE_ADDRESS=
# mainnet | testnet
NETWORK=testnet

API_SECURE=false
# Default is "public-pool", you can change it to any string it will be removed if it will make the block or coinbase script too big
POOL_IDENTIFIER="public-pool"
```

So the problem arose here

```
$ npm run start

> public-pool@0.0.1 start
> nest start

[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [NestFactory] Starting Nest application...
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +117ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [InstanceLoader] HttpModule dependencies initialized +1ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [InstanceLoader] CacheModule dependencies initialized +0ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +1ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +37ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [InstanceLoader] ClientStatisticsModule dependencies initialized +1ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [InstanceLoader] ClientModule dependencies initialized +0ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [InstanceLoader] AddressSettingsModule dependencies initialized +0ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [InstanceLoader] TelegramSubscriptionsModule dependencies initialized +0ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [InstanceLoader] BlocksModule dependencies initialized +0ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [InstanceLoader] RpcBlocksModule dependencies initialized +0ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [InstanceLoader] AppModule dependencies initialized +4ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [RoutesResolver] AppController {/api}: +32ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [RouterExplorer] Mapped {/api/info, GET} route +5ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [RouterExplorer] Mapped {/api/pool, GET} route +1ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [RouterExplorer] Mapped {/api/network, GET} route +1ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [RouterExplorer] Mapped {/api/info/chart, GET} route +1ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [RoutesResolver] ClientController {/api/client}: +0ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [RouterExplorer] Mapped {/api/client/:address, GET} route +1ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [RouterExplorer] Mapped {/api/client/:address/chart, GET} route +1ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [RouterExplorer] Mapped {/api/client/:address/:workerName, GET} route +1ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [RouterExplorer] Mapped {/api/client/:address/:workerName/:sessionId, GET} route +1ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [RoutesResolver] AddressController {/api/address}: +0ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [RouterExplorer] Mapped {/api/address/settings, PATCH} route +1ms
[Nest] 13117  - 10/22/2024, 10:43:11 PM     LOG [NestApplication] Nest application successfully started +24ms
API listening on http://0.0.0.0:3334
Could not reach RPC host
Error getmininginfo 404 - undefined
Error getmininginfo 404 - undefined
Error getmininginfo 404 - undefined
Error getmininginfo 404 - undefined
Error getmininginfo 404 - undefined
Error getmininginfo 404 - undefined
Error getmininginfo 404 - undefined
Error getmininginfo 404 - undefined
Error getmininginfo 404 - undefined
Error getmininginfo 404 - undefined
Error getmininginfo 404 - undefined
Error getmininginfo 404 - undefined
Error getmininginfo 404 - undefined
Error getmininginfo 404 - undefined
Error getmininginfo 404 - undefined
Error getmininginfo 404 - undefined
Error getmininginfo 404 - undefined
Error getmininginfo 404 - undefined
Error getmininginfo 404 - undefined
Stratum server is listening on port 3333
Error getmininginfo 404 - undefined
```

**Comment by Demontager** [comment]
Found problem, i had misconfiguration in .env To get it work as expected BITCOIN_RPC_URL variable should be defined without port number. In my case
BITCOIN_RPC_URL=http://192.168.1.181

Antminer S9 connects to pool and getting job.
```
[Nest] 6983  - 11/02/2024, 11:23:17 PM     LOG [RouterExplorer] Mapped {/api/client/:address/chart, GET} route +0ms
[Nest] 6983  - 11/02/2024, 11:23:17 PM     LOG [RouterExplorer] Mapped {/api/client/:address/:workerName, GET} route +1ms
[Nest] 6983  - 11/02/2024, 11:23:17 PM     LOG [RouterExplorer] Mapped {/api/client/:address/:workerName/:sessionId, GET} route +1ms
[Nest] 6983  - 11/02/2024, 11:23:17 PM     LOG [RoutesResolver] AddressController {/api/address}: +0ms
[Nest] 6983  - 11/02/2024, 11:23:17 PM     LOG [RouterExplorer] Mapped {/api/address/settings, PATCH} route +1ms
[Nest] 6983  - 11/02/2024, 11:23:17 PM     LOG [NestApplication] Nest application successfully started +20ms
API listening on http://0.0.0.0:3334
Bitcoin RPC connected
block height change
Stratum server is listening on port 3333
Killing dead clients
block height change
Killing dead clients
Killing dead clients
New client ID: : d1d2dd6f, ::ffff:192.168.1.170:42397
getblocktemplate tx count: 3548
getblocktemplate tx count: 3549
getblocktemplate tx count: 3550
getblocktemplate tx count: 3551

```
